---
# ansible vmware inventory configuration
#
# 'config.yml' and environment variables can be used as configuration.
# They can be used separately or together. environment variables will always
# take precedence.
#
# hostname: str
#   * required: true
#   * default: None
#   * desc: hostname/ip of vcenter
#   * env: VMWARE_HOSTNAME=vcenter.example.com
# username: str
#   * required: true
#   * default: None
#   * desc: username for vcenter
#   * env: VMWARE_USERNAME=username
# password: str
#   * required: true
#   * default: None
#   * desc: password for vcenter
#   * env: VMWARE_PASSWORD=password
# validate_certs: bool
#   * required: false
#   * default: true
#   * desc: enables/disables ssl certificate verification
#   * env: VMWARE_VALIDATE_CERTS=false
# clusters: list
#   * required: true
#   * default: None
#   * desc: cluster(s) to query
#   * env: VMWARE_CLUSTERS="Cluster1,Cluster2,Cluster3"
# cache: bool
#   * required: false
#   * default: false
#   * desc: enable inventory caching
#   * env: VMWARE_CACHE=true
# cache_time: int
#   * required: false
#   * default: 300
#   * desc: length of time in seconds to keep the cache. default is 300s or 5m.
#   * env: VMWARE_CACHE_TIME=3600
# cache_path: str
#   * required: false
#   * default: {script_dir}/.vminv.json
#   * desc: path and filename to store cache. defaults to the same directory
#           as the script.
#   * env: VMWARE_CACHE_FILE=/tmp/vminv.json
# gather_vm_facts: bool
#   * required: false
#   * default: false
#   * desc: gathers various vm facts for hostvars
#   * warning: decreases performance
#   * env: VMWARE_GATHER_VM_FACTS=true
# custom_values_filters: list
#   * required: false
#   * default: None
#   * desc: only group based on a keyword filter
#   * env: VMWARE_CUSTOM_VALUES_FILTERS="Environment,Function"
# custom_values_groupby_keyval: bool
#   * required: false
#   * default: true
#   * desc: creates groups in the form of key_value from the custom values
#   * env: VMWARE_GROUPBY_CUSTOM_VALUES=false
# custom_values_groupby_val: list
#   * required: false
#   * default: None
#   * desc: creates groups based off the value of defined custom values
#   * env: VMWARE_CUSTOM_VALUES_GROUPBY_VAL="Environment"
# properties: list({name: str, group: bool})
#   * required: false
#   * default: None
#   * desc: properties to query and optionally group by the value.
#           use group_alias for boolean values. will use the provided name
#           and only group when the value is true.
#           use exclude_if to exclude the host based on the provided value.
#   * env: VMWARE_PROPERTIES='[{"name":"config.guestId", "group":true}]'
#   * example:
#     - name: config.guestId
#       group: true
#     - name: config.template
#       group: true
#       group_alias: template
#     - name: runtime.powerState
#       exclude_if: poweredoff
#

#
# sample
#
hostname: vcenter.example.com
username: user
password: pass
clusters:
  - Cluster Name
properties:
  - name: config.guestId
    group: true
  - name: runtime.powerState
    exclude_if: poweredoff
  - name: config.annotation
  - name: summary.config.memorySizeMB
  - name: summary.config.numCpu
  - name: config.uuid
  - name: config.template
    group: true
    group_alias: template
